"""Captions of the generated tables read as plain academic prose."""
import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "analysis"))
from paper_table_text import _academic_caption  # noqa: E402

TABLES = ROOT / "paper" / "paper" / "tables"
if not TABLES.exists():
    TABLES = ROOT / "paper" / "tables"
USED = """candidate_coverage cap_conditioning cond_audit distill_confirm distill_forms_audit distill_paired
final_deliverables locked_rule main_context main_final main_prediction_v2 model_arch models_domains musique_scope
p1v2 p2v2_test p3_check panel_prune panel_quant pred_config_prune pred_config_qd pred_full pred_source prune_repeat
qa_scope quant2d_coef quant_ident quant_threeway round3_coef round3_prune round3_quant rule_confirm
rule_confirm_by_state rule_decomp selection_feasible shared_structure v53_loso v55_loso v56_forms""".split()
PATCHED = {
    "models_domains": r"Eq.~\ref{eq:quant2d}",
    "pred_full": r"Appendix Tables~\ref{tab:pred_source}--\ref{tab:pred_config_qd}",
    "v55_loso": r"Section~\ref{sec:unseen_settings}",
    "round3_prune": r"Appendix Table~\ref{tab:round3_coef}",
}
FORBIDDEN = {
    r"\.py\b": "generator file name",
    r"[Gg]enerated by": "provenance clause",
    r"The register is": "register path",
    r"\bV\d{2}\b": "internal experiment code",
    r"\?": "question mark",
    r"(CI|MAE) denotes [^.]*\..*\1 denotes": "duplicated abbreviation sentence",
    r"(CI|MAE) means [^.]*\..*\1 denotes": "duplicated abbreviation sentence",
    r"\bevery\b": "absolute quantifier",
}


def captions(text):
    out = []
    for match in re.finditer(r"\\caption(?:\*|\[\])?\{", text):
        i, depth = match.end(), 1
        while depth:
            if text[i] == "{" and text[i - 1] != "\\":
                depth += 1
            elif text[i] == "}" and text[i - 1] != "\\":
                depth -= 1
            i += 1
        out.append(text[match.end():i - 1])
    return out


@pytest.mark.parametrize("name", USED)
def test_caption_is_plain_academic_prose(name):
    path = TABLES / f"{name}.tex"
    if not path.exists():
        pytest.skip(f"{name}.tex is not generated in this checkout")
    for caption in captions(path.read_text()):
        prose = re.sub(r"\$(?:\\.|[^$])*\$", "", caption)
        for pattern, why in FORBIDDEN.items():
            assert not re.search(pattern, prose), f"{name}: {why}: {caption[:160]}"
        assert prose.count("``") <= 1, f"{name}: more than one quoted phrase"
        assert " = " not in prose, f"{name}: equation-style prose: {caption[:160]}"


@pytest.mark.parametrize("name,fragment", sorted(PATCHED.items()))
def test_patched_reference_fragments_survive(name, fragment):
    path = TABLES / f"{name}.tex"
    if not path.exists():
        pytest.skip(f"{name}.tex is not generated in this checkout")
    assert fragment in path.read_text()


def test_academic_caption_removes_provenance_sentences():
    text = r"\caption{The table lists x. The table was generated by \texttt{a\_b.py} from \texttt{c.json}. The register is \texttt{r.json}. CI means confidence interval. CI denotes confidence interval.}"
    out = _academic_caption(text)
    assert out == r"\caption{The table lists x. CI denotes confidence interval.}"


LONG_ALLOWED = {"main_prediction_v2": 100}  # Separate author-owned task.


@pytest.mark.parametrize("name", USED)
def test_caption_is_short(name):
    """Captions state what the table shows, the unit and the reading rule; about four typeset lines."""
    path = TABLES / f"{name}.tex"
    if not path.exists():
        pytest.skip(f"{name}.tex is not generated in this checkout")
    for caption in captions(path.read_text()):
        if "Continued" in caption:
            continue
        prose = re.sub(r"\$(?:\\.|[^$])*\$", "M", caption)
        prose = re.sub(r"\\[a-zA-Z]+\*?(?:\[[^\]]*\])?(?:\{[^{}]*\})?", " ", prose)
        words = len(prose.split())
        assert words <= LONG_ALLOWED.get(name, 60), f"{name}: caption has {words} words"
