#!/usr/bin/env python3
"""CPU-only Fig. 1; also holds the shared style and provenance helpers for Figs. 2–4.

Run from any directory: python /path/to/analysis/plot_fig1_responses.py.
Only reads result JSON; never imports analysis modules that rebuild results/TeX.
"""
import json
import os
from pathlib import Path
import re
import tempfile

os.environ.setdefault("MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "scaling-down-figure-mpl"))
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import font_manager
from matplotlib.lines import Line2D
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
FIGS = ROOT / "paper/figs"
NOTES = ROOT / "paper/docs/FIGURE_BUILD_NOTES.md"
CAPS = ("math", "code", "qa")
CAP_LABEL = {"math": "Math", "code": "Code", "qa": "QA"}
# Method colours also identify their headline candidate throughout all four figures.
COLORS = {
    "pruning": "#2166ac", "power": "#2166ac",
    "quantization": "#d97718", "full": "#d97718",
    "distillation": "#22834a", "E": "#22834a",
    "A2": "#8662a6", "A1": "#258d9e", "cont": "#b34e83",
    "median_curve": "#737373", "per_bit_median": "#737373",
    "constant": "#444444", "zero": "#999999",
    "same_cap": "#ad416b", "cross_selected": "#795548",
    "train_mean": "#444444", "measured": "#202020",
}


def setup_style():
    """Font setup copied from plot_v9_blocks_appendix.py, with >=8 pt text."""
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Nimbus Roman", "Liberation Serif", "Times New Roman"],
        "font.weight": "bold", "axes.labelweight": "bold", "axes.titleweight": "bold",
        "pdf.fonttype": 42, "ps.fonttype": 42,
        "font.size": 9, "axes.labelsize": 9, "axes.titlesize": 10,
        "xtick.labelsize": 8, "ytick.labelsize": 8, "legend.fontsize": 8,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.unicode_minus": True, "savefig.dpi": 300,
    })
    # This matplotlib version embeds Nimbus CFF/OTF as a mismatched PDF fonttype 42.
    # Use the copied setup's Times-metric TrueType fallback when necessary.
    families = plt.rcParams["font.serif"]
    resolved = Path(font_manager.findfont(font_manager.FontProperties(family=families, weight="bold")))
    if resolved.suffix.lower() == ".otf":
        fallback = font_manager.findfont(font_manager.FontProperties(family="Liberation Serif", weight="bold"),
                                         fallback_to_default=False)
        plt.rcParams["font.serif"] = ["Liberation Serif", "Nimbus Roman", "Times New Roman"]
        resolved = Path(fallback)
    print(f"STYLE bold Times-metric font: {resolved}; PDF fonttype 42; minimum 8 pt; PNG 300 dpi")


class Audit:
    """Print exact inputs/rules and replace only this figure's generated notes section."""

    def __init__(self, number, title):
        self.number, self.title = number, title
        self.files, self.rules, self.limitations, self.outputs = [], [], [], []

    def read(self, path):
        path = Path(path)
        if not path.is_absolute():
            path = ROOT / path
        print(f"READ {path}")
        data = json.loads(path.read_text())
        rel = str(path.relative_to(ROOT))
        if rel not in self.files:
            self.files.append(rel)
        return data

    def rule(self, message):
        print(f"SELECT {message}")
        self.rules.append(message)

    def omit(self, message):
        print(f"LIMITATION {message}")
        self.limitations.append(message)

    def output(self, path):
        print(f"WROTE {path}")
        self.outputs.append(str(path.relative_to(ROOT)))

    def save(self, fig, stem):
        FIGS.mkdir(parents=True, exist_ok=True)
        # Fixed metadata makes reruns byte-for-byte reproducible.
        for ext in ("pdf", "png"):
            path = FIGS / f"{stem}.{ext}"
            kw = {"metadata": {"CreationDate": None, "ModDate": None}} if ext == "pdf" else {}
            fig.savefig(path, dpi=300, **kw)
            self.output(path)
        plt.close(fig)

    def finish(self):
        header = (
            "# Figure build notes\n\n"
            "Generated by the four `analysis/plot_fig*.py` scripts. Run each with Python; "
            "paths resolve relative to the script, not the working directory. Dependencies: "
            "NumPy and matplotlib. Agg backend; CPU only; no model execution or fitting. "
            "The scripts only write their PDF/PNG outputs, the Fig. 1 caption, and this document. "
            "No existing result JSON, register, or TeX is changed; no mirror is written under "
            "`paper/code/analysis/`, following the user's narrower output allowlist.\n\n"
            "Fonts use the bold Nimbus Roman / Liberation Serif / Times New Roman setup from "
            "`analysis/plot_v9_blocks_appendix.py`, with embedded PDF fonts (fonttype 42), "
            "8 pt minimum at the saved physical size, and PNGs at 300 dpi. Preserve native "
            "dimensions when placing these figures to retain that minimum. When Nimbus resolves "
            "to a CFF/OTF font, use the copied setup's bold Liberation Serif TrueType fallback "
            "to avoid a PDF fonttype/embedded-file mismatch in this matplotlib version. "
            "The selected font path is printed as STYLE. Pruning/power = blue; "
            "quantization/full = orange; distillation/E-only = green; A2 = purple; A1 = teal; "
            "median baselines = grey; constant/mean = charcoal. Capability order: math, code, QA. "
            "All gain axes use reference MAE minus candidate MAE, positive = candidate better. "
            "Fig. 1 instead shows the specified raw loss response (compressed minus dense). "
            "Each plot keeps its reported native token units; there is no tokenizer conversion, "
            "pooled cross-panel score, fitted smoothing, or invented uncertainty.\n\n"
            "Validation: each script checks the relevant numerical identities before saving. "
            "Missing optional quantities are printed as LIMITATION and recorded below. "
            "Each READ line is an actual JSON read, not merely a cited upstream dependency.\n\n"
        )
        section = f"<!-- FIGURE {self.number} START -->\n## Figure {self.number}: {self.title}\n\n"
        section += "Outputs: " + ", ".join(f"`{p}`" for p in self.outputs) + ".\n\n"
        section += "Selection and calculations:\n\n" + "".join(f"- {s}\n" for s in self.rules)
        section += "\nLimitations and specification resolutions:\n\n"
        section += "".join(f"- {s}\n" for s in self.limitations) or "- None; all requested quantities recovered.\n"
        section += "\nExact data files read:\n\n" + "".join(f"- `{p}`\n" for p in self.files)
        section += f"\n<!-- FIGURE {self.number} END -->\n"
        old = NOTES.read_text() if NOTES.exists() else ""
        sections = {}
        for match in re.finditer(r"<!-- FIGURE (\d+) START -->.*?<!-- FIGURE \1 END -->", old, re.S):
            sections[int(match.group(1))] = match.group(0) + "\n"
        sections[self.number] = section
        NOTES.parent.mkdir(parents=True, exist_ok=True)
        NOTES.write_text(header + "\n".join(sections[n] for n in sorted(sections)))
        print(f"WROTE {NOTES} (Figure {self.number} section)")


def checked_close(actual, expected, description):
    if not np.allclose(actual, expected, rtol=1e-8, atol=1e-10):
        raise ValueError(f"{description}: {actual!r} != {expected!r}")


def load_distillation(audit, summary):
    """Reconstruct precisely the trajectory cohort used by v41_distill_newpool.py."""
    base = ROOT / "results/v12-distill/gemma3-1b"
    patterns = ("gpt-5.6-luna_full_75_uxseen*", "gpt-5.6-luna_full_600_uxseen*",
                "gpt-5.6-luna_full_225_lora_dseed*")
    points = []
    for pattern in patterns:
        for run in sorted(base.glob(pattern)):
            if not (run / "eval.json").exists():
                audit.omit(f"{run.name}: no final eval.json; excluded as in the v41 cohort builder.")
                continue
            final = audit.read(run / "eval.json")
            log = audit.read(run / "train_log.json") if (run / "train_log.json").exists() else None
            snapshots = []
            for path in sorted(run.glob("trajectory/update-*/eval.json")):
                ev = audit.read(path)
                if ev["completion_tokens_seen"] <= 0:
                    continue  # Dense anchors are never scored as artificial observations.
                try:
                    delta = {c: ev["post_training"][c] - ev["dense"][c] for c in CAPS}
                    checked_close(list(delta.values()), [ev["delta"][c] for c in CAPS], str(path))
                    checked_close([ev["dense"][c] for c in CAPS],
                                  [final["dense"][c] for c in CAPS], f"dense anchor {path}")
                    if log is not None:
                        entry = next(r for r in log["loss_curve"] if r["step"] == ev["updates"])
                        processed, pool = entry["tokens_seen"], entry["unique_data_pool_tokens"]
                        checked_close(processed, ev["processed_tokens"], f"token budget {path}")
                        checked_close(pool, ev["unique_data_pool_tokens"], f"pool tokens {path}")
                    else:
                        processed, pool = ev["processed_tokens"], ev["unique_data_pool_tokens"]
                        audit.omit(f"{run.name}: no train_log.json; using recorded snapshot token accounting.")
                    if pool <= 0:
                        raise ValueError("nonpositive unique pool tokens")
                except (KeyError, StopIteration) as exc:
                    audit.omit(f"{path.relative_to(ROOT)}: cannot recover loss/token fields ({exc}); skipped.")
                    continue
                snapshots.append({"run": run.name, "pool": final["n_per_domain"],
                                  "E": processed / pool, "Tc": ev["completion_tokens_seen"],
                                  "delta": delta, "test": final["n_per_domain"] == 225})
            for budget_index, point in enumerate(snapshots):
                point["budget_index"] = budget_index
                points.append(point)
    endpoint = [p for p in points if not p["test"]]
    test = [p for p in points if p["test"]]
    if endpoint:
        checked_close(len(endpoint), summary["n_endpoint_checkpoints"], "v41 endpoint count")
        checked_close([min(p["E"] for p in endpoint), max(p["E"] for p in endpoint)],
                      summary["endpoint_E_range"], "endpoint E range")
    if test:
        checked_close(len({p["run"] for p in test}), summary["n_u225_runs"], "v41 test run count")
        checked_close([min(p["E"] for p in test), max(p["E"] for p in test)],
                      summary["u225_E_range"], "U225 E range")
        for cap in CAPS:
            fits = summary["by_cap"][cap]["fits"]
            for kind in ("constant", "E"):
                errors = [abs(p["delta"][cap] - predict_reuse(fits[kind], kind, p["E"])) for p in test]
                checked_close(np.mean(errors), summary["by_cap"][cap]["mae"][kind], f"v41 {cap}/{kind} MAE")
    audit.rule("Distillation cohort exactly follows v41: " + ", ".join(patterns) +
               f"; {len(endpoint)} endpoint and {len(test)} U225 nonzero trajectory snapshots. "
               "Final evals supply/verify dense anchors; final training endpoints and other recipes are not "
               "added to the frozen-fit cohort. E = matching train_log.loss_curve.tokens_seen / "
               "unique_data_pool_tokens; delta = snapshot.post_training[cap] - snapshot.dense[cap].")
    audit.rule("Constant = fits.constant[0]; E-only = fits.E[0] + fits.E[1] * natural_log(E). "
               "Coefficients are read unchanged, never refitted. Recovered E ranges and U225 MAEs "
               "are checked against v41. U75 uxseenE low-budget runs are included in its 18-point fit cohort.")
    return points


def predict_reuse(beta, kind, E):
    return beta[0] + (beta[1] * np.log(E) if kind == "E" else np.zeros_like(E, dtype=float))


def main():
    setup_style()
    audit = Audit(1, "Measured responses and frozen predictions")
    sources = {size: audit.read(f"results/v49-p1v2/compare_pythia-{size}@step112000.json")["protocols"]["A"]
               for size in ("1b", "6.9b")}
    summary = audit.read("results/v41-distill-newpool/summary.json")
    points = load_distillation(audit, summary)
    audit.rule("Pruning and quantization: protocol A, Pythia 1B and 6.9B at step112000; "
               "rows selected by cap without pooling capabilities. Density points 0.9, 0.8, 0.75, "
               "0.7, 0.65, 0.6, 0.55; shade d < 0.6. Plot recorded actual and pred fields. "
               "6.9B uses squares and lighter opacity; its power curve is omitted per the requested overlay.")
    audit.rule("Integer bits are equally spaced categories [8, 6, 5, 4, 3]. Measured points are filled; "
               "full predictions are hollow, with thin dashed guides only; per-bit median uses dotted guides. "
               "Every 5-bit row must have rule='interp(4,6)'. No continuous bit-width law is drawn.")
    audit.omit("There is no measured density 0.85 in the selected v49 files; no point is interpolated there. "
               "The displayed median_curve is the specifically requested baseline, not claimed best for every source/regime.")
    fig, axes = plt.subplots(3, 3, figsize=(8.4, 8.8))
    fig.subplots_adjust(left=.085, right=.985, bottom=.09, top=.815, wspace=.42, hspace=.42)
    bits = [8, 6, 5, 4, 3]
    for i, cap in enumerate(CAPS):
        ap, aq, ad = axes[i]
        for ax in (ap, aq, ad):
            ax.axhline(0, color="#bbbbbb", lw=.6, zorder=0)
            ax.grid(axis="y", color="#eeeeee", lw=.6)
        ap.axvspan(.535, .6, color="#f1dfbf", alpha=.55, zorder=0)
        for size in ("6.9b", "1b"):
            alpha = .45 if size == "6.9b" else 1
            marker = "s" if size == "6.9b" else "o"
            prune = sorted((r for r in sources[size]["rows_prune"] if r["cap"] == cap), key=lambda r: -r["d"])
            x = [r["d"] for r in prune]
            ap.plot(x, [r["actual"] for r in prune], marker, color=COLORS["measured"], ms=3.8, alpha=alpha, zorder=5)
            for candidate, ls in (("power", "-"), ("A2", "--"), ("median_curve", ":")):
                if size == "6.9b" and candidate == "power":
                    continue
                ap.plot(x, [r[candidate]["pred"] for r in prune], ls, lw=1.2,
                        color=COLORS[candidate], alpha=alpha)
            quant = {r["bit"]: r for r in sources[size]["rows_quant"] if r["cap"] == cap}
            if quant[5]["rule"] != "interp(4,6)":
                raise ValueError(f"Unexpected 5-bit prediction rule for {size}/{cap}")
            for candidate in ("actual", "full", "per_bit_median"):
                y = [quant[b]["actual"] if candidate == "actual" else quant[b][candidate]["pred"] for b in bits]
                color = COLORS["measured"] if candidate == "actual" else COLORS[candidate]
                aq.plot(range(5), y, linestyle=":" if candidate == "per_bit_median" else "--",
                        lw=.65, color=color, alpha=alpha, marker=marker, ms=3.8,
                        markerfacecolor=color if candidate == "actual" else "white", zorder=3)
        ap.set_xlim(.915, .535)
        ap.set_xticks([.9, .8, .7, .6, .55], [".9", ".8", ".7", ".6", ".55"])
        ap.set_ylabel(f"{CAP_LABEL[cap]}\nΔL (nats/token)")
        aq.set_xticks(range(5), ["8", "6", "5*", "4", "3"])
        aq.set_xlim(-.3, 4.3)
        for pool, marker in ((75, "o"), (600, "s"), (225, "D")):
            pp = [p for p in points if p["pool"] == pool]
            if pp:
                ad.plot([p["E"] for p in pp], [p["delta"][cap] for p in pp], linestyle="none",
                        marker=marker, ms=4, markeredgewidth=.8, color=COLORS["measured"],
                        markerfacecolor="white" if pool == 225 else COLORS["measured"], zorder=4)
        if points:
            e = np.geomspace(*summary["endpoint_E_range"], 200)
            for kind, ls in (("constant", ":"), ("E", "-")):
                beta = summary["by_cap"][cap]["fits"][kind]
                ad.plot(e, predict_reuse(beta, kind, e), ls, color=COLORS[kind], lw=1.3)
        else:
            audit.omit(f"{cap}: no recoverable distillation points; no data curve plotted.")
        ad.set_xscale("log")
        ad.set_xticks([1, 2, 5, 10], ["1", "2", "5", "10"])
        ad.minorticks_off()
        ad.set_ylabel("δ (nats/token)", labelpad=1)
        if i == 2:
            ap.set_xlabel("Density d")
            aq.set_xlabel("Integer bits")
            ad.set_xlabel("Reuse E = T / D_U (log scale)")
    handles = [
        [Line2D([], [], marker="o", ls="", color=COLORS["measured"], label="1B measured"),
         Line2D([], [], color=COLORS["power"], label="1B power (frozen)"),
         Line2D([], [], color=COLORS["A2"], ls="--", label="A2 (frozen)"),
         Line2D([], [], color=COLORS["median_curve"], ls=":", label="Median curve"),
         Line2D([], [], color=COLORS["measured"], marker="s", ls="", alpha=.45, label="6.9B (light overlays)")],
        [Line2D([], [], marker="o", ls="", color=COLORS["measured"], label="1B measured"),
         Line2D([], [], color=COLORS["full"], marker="o", mfc="white", ls="--", lw=.65, label="Full (frozen)"),
         Line2D([], [], color=COLORS["per_bit_median"], ls=":", label="Per-bit median"),
         Line2D([], [], marker="s", ls="", color=COLORS["measured"], alpha=.45, label="6.9B (light overlays)")],
        [Line2D([], [], marker=m, ls="", color=COLORS["measured"], mfc="white" if u == 225 else COLORS["measured"],
                label=f"U{u} {'test' if u == 225 else 'endpoint'}") for u, m in ((75, "o"), (600, "s"), (225, "D"))]
        + [Line2D([], [], color=COLORS[k], ls=l, label=n) for k, l, n in
           (("constant", ":", "Constant (frozen)"), ("E", "-", "E-only (frozen)"))],
    ]
    titles = ("Pruning · Pythia @112k", "Quantization · Pythia @112k", "Distillation · Gemma-3-1B")
    for j in range(3):
        box = axes[0, j].get_position()
        fig.text(box.x0, .975, titles[j], fontsize=10, va="top")
        fig.legend(handles=handles[j], loc="upper left", bbox_to_anchor=(box.x0, .95),
                   frameon=False, borderaxespad=0, handlelength=1.9, labelspacing=.4)
    fig.text(axes[0, 0].get_position().x0, .835, "Shaded: d < .6 extrapolation", fontsize=8)
    axes[0, 1].text(.03, .97, "*5-bit: rule\n(interp of 4/6)", transform=axes[0, 1].transAxes, va="top", fontsize=8)
    qa_bias = []
    for budget in sorted({p["budget_index"] for p in points if p["test"]}):
        pp = [p for p in points if p["test"] and p["budget_index"] == budget]
        beta = summary["by_cap"]["qa"]["fits"]["E"]
        bias = np.mean([predict_reuse(beta, "E", p["E"]) - p["delta"]["qa"] for p in pp])
        tokens = np.mean([p["Tc"] for p in pp])
        qa_bias.append(f"{tokens / 1000:.0f}k: {bias:+.2f}")
        audit.rule(f"QA U225 budget {budget + 1}: mean completion tokens={tokens:.1f}, "
                   f"n={len(pp)} snapshots; E-only bias (prediction minus observed)={bias:+.9f} nats/token.")
    if qa_bias:
        axes[2, 2].text(.03, .97, "U225 QA bias (pred − obs)\n" + "; ".join(qa_bias),
                        transform=axes[2, 2].transAxes, va="top", fontsize=8,
                        bbox={"facecolor": "white", "edgecolor": "none", "alpha": .85, "pad": 1})
    audit.omit("Trajectory checkpoints within a run share training and probes; no independent-seed "
               "error bars are inferred. T-only and 2D curves are not requested and are not reduced "
               "to an E curve by inventing a token budget.")
    fig.text(.5, .025, "Raw response = compressed − dense loss; negative = lower loss. Columns use separate native-token axes.",
             ha="center", fontsize=8)
    audit.save(fig, "predictive_responses")
    caption = FIGS / "predictive_responses_caption.txt"
    caption.write_text(
        "Measured capability responses and frozen predictions. Rows: math, code, QA. "
        "Pythia pruning/quantization use protocol A at step112000: 1B in dark circles, "
        "6.9B in lighter squares. Shading marks density below 0.6. Quantization uses "
        "categorical integer bits; thin guides do not assert a continuous law, and 5-bit "
        "predictions are the frozen interpolation rule between 4 and 6 bits. Distillation "
        "uses Gemma-3-1B U75/U600 endpoint checkpoints (filled) and U225 held-out checkpoints "
        "(hollow); lines are the saved constant and log(E) fits. QA annotations give mean "
        "prediction-minus-observation bias at the two measured U225 completion-token budgets. "
        "Raw loss changes are in nats per native token, compressed minus dense; axes are not shared "
        "across tokenizers. All checkpoints are measured, with no new fitting or smoothing.\n\n"
        "Exact JSON files read:\n" + "\n".join(audit.files) + "\n\nSelection rules:\n"
        + "\n".join(audit.rules) + "\n\nLimitations:\n" + "\n".join(audit.limitations) + "\n"
    )
    audit.output(caption)
    audit.finish()


if __name__ == "__main__":
    main()
