#!/usr/bin/env python3
"""Headline subset of the compact prediction table for the main text. Reads paper/paper/tables/pred_main.tex (generated by
v52), keeps the rows whose label starts with one of KEEP, writes paper/paper/tables/pred_headline.tex (label tab:pred_main)
and paper/paper/tables/pred_full.tex (all rows, label tab:pred_full, [H]) for Appendix D. Numbers are copied verbatim."""
import re; from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; T = ROOT / "paper/paper/tables"
KEEP = ["prune: fixed $d$", "quant: fixed $b$", "distill: $\\delta_c$", "prune: stage 96k", "quant: new stage 96k (160M/410M/1.4B), $b\\ge4$",
        "prune: $d$ 0.65/0.55", "prune: 1B@32k+112k, $d$ 0.9--0.6", "prune: 1B@32k+112k, $d=0.55$", "prune: 6.9B@32k+112k, $d$ 0.9--0.6",
        "quant: 6.9B@32k+112k, $b\\ge4$", "distill: unseen pool U225", "KD 270M", "KD 1B", "KD 4B"]
src = (T / "pred_main.tex").read_text(); lines = src.split("\n")
out, kept, dropped = [], 0, 0
for ln in lines:
    body = ln.strip()
    is_row = body.endswith("\\\\") and "&" in body and not body.startswith("\\multicolumn") and not body.startswith("Test")
    if is_row:
        if any(body.startswith(k) for k in KEEP): out.append(ln); kept += 1
        else: dropped += 1
    else: out.append(ln)
head = "\n".join(out)
head = head.replace("\\caption{\\scriptsize Prediction tests, all three arms", "\\caption{\\scriptsize Prediction tests, headline rows of all three arms (the complete list is Table~\\ref{tab:pred_full} in Appendix~\\ref{sec:app_results})", 1)
if "headline rows" not in head: head = head.replace("\\caption{", "\\caption{Headline prediction tests (complete list in Table~\\ref{tab:pred_full}). ", 1)
(T / "pred_headline.tex").write_text(head)
full = src.replace("\\label{tab:pred_main}", "\\label{tab:pred_full}").replace("\\begin{table}[!t]", "\\begin{table}[H]", 1).replace("\\begin{table}[t]", "\\begin{table}[H]", 1)
full = full.replace("\\caption{\\scriptsize Prediction tests, all three arms", "\\caption{\\scriptsize Prediction tests, all three arms, complete list", 1)
(T / "pred_full.tex").write_text(full)
print(f"kept {kept} rows, dropped {dropped}; wrote pred_headline.tex and pred_full.tex")
