#!/usr/bin/env python3
"""Render the primary and full A13 tables from saved, read-only accounting.

Run: python -B analysis/a13_dreq_table.py
Writes dreq_main and dreq_full tables and their provenance sidecars only.
"""
from __future__ import annotations

import argparse
import hashlib
from itertools import product
import json
from pathlib import Path

try:
    from .paper_table_layout import house_style
except ImportError:  # run as a script
    import sys, pathlib
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    from paper_table_layout import house_style


try:
    from .paper_artifacts import ROOT, Artifacts, output_path
except ImportError:
    from paper_artifacts import ROOT, Artifacts, output_path


ACCOUNTING = Path("results/a13-dreq-accounting/accounting.json")
PRIMARY_TAU = 0.25
READOUTS = {
    "math:MATH-500": "Math",
    "code:MBPP": "Code",
    "qa:2Wiki-probe": "Original 2Wiki",
    "qa:2Wiki-fresh": "Fresh 2Wiki",
    "qa:MuSiQue": "MuSiQue",
    "qa:TriviaQA": "TriviaQA",
}
STUDENTS = {"gemma3-1b": "1 billion", "gemma3-4b": "4 billion"}
METHODS = {
    "boundary_loglinear": "Boundary relation",
    "fixed_reuse": "Fixed reuse",
    "student_isotonic": "Per-student interpolation",
}
OUTCOMES = {
    "crossed": "crossed inside the tested pools",
    "lower_bound": "lower bound at the largest pool",
    "upper_bound": "upper bound at the smallest pool",
    "replicate_ambiguous": "seeds disagree",
    "non_monotone": "non-monotone",
}
SEED_DESIGN = (
    "The largest pool varies the training seed; smaller pools vary the pool draw. "
    "Intervals are observed brackets, not confidence intervals. "
)
MAIN_CAPTION = (
    r"Measured data requirements at the primary loss tolerance $\tau=0.25$ nats "
    "are shown for both Gemma 3 students, identified by parameter count. "
    "Budgets count supervised training tokens, including reuse; k means thousands. "
    + SEED_DESIGN +
    "Each boundary-rule recommendation gives a pool size followed by inside or its "
    "natural-log distance to the interval. Inside includes bracket endpoints and "
    "does not verify success. For a one-sided bound, distance is only a lower bound. "
    "Unresolved means no measured interval; none means the rule abstains."
)
FULL_CAPTION = (
    "Full measured data-requirement accounting covers all four loss tolerances "
    "and both Gemma 3 students, identified by parameter count. Budgets count "
    "supervised training tokens, including reuse; pool sizes count independent "
    "supervised tokens, and k means thousands. "
    + SEED_DESIGN +
    "Each method cell reports natural-log distances for the boundary rule and "
    "the loss rule, in that order. Zero means compatibility with the interval, "
    "including bracket endpoints, and does not verify success. A leading greater-than-or-equal sign marks a distance lower "
    "bound for a one-sided interval. Log interval width is the natural log of the "
    "upper endpoint divided by the lower endpoint; one-sided log widths are "
    "unbounded. Unresolved means no measured interval; none means the rule abstains. "
    "Seeds disagree when a tested pool tier has both passing and failing runs. "
    "Non-monotone means average loss increases with pool size."
)
GENERATED = "% Generated by analysis/a13_dreq_table.py; do not edit."


def validate_requests(requests):
    expected = set(product(READOUTS, STUDENTS, (50000, 100000, 200000), (0., .1, .25, .5)))
    actual = [(r["readout"], r["student"], r["nominal_supervised_tokens"], r["tau"])
              for r in requests]
    if len(actual) != len(expected) or set(actual) != expected:
        raise ValueError("Expected exactly the 144 distinct A13 requests")
    if len({r["request_id"] for r in requests}) != len(expected):
        raise ValueError("Duplicate A13 request identifiers")


def ordered_requests(requests, readout, tau=None):
    return sorted((r for r in requests if r["readout"] == readout
                   and (tau is None or r["tau"] == tau)),
                  key=lambda r: (r["student"], r["tau"], r["nominal_supervised_tokens"]))


def interval_cell(request):
    crossing = request["measured_crossing"]
    if crossing["interval"] is None:
        return "unresolved"
    lo, hi = crossing["interval"]
    if crossing["status"] == "crossed":
        return rf"$[{lo/1000:.3f},\allowbreak\,{hi/1000:.3f}]$"
    if crossing["status"] == "lower_bound":
        return rf"$>{lo/1000:.3f}$"
    return rf"$\leq {hi/1000:.3f}$"


def distance_cell(row, *, describe_inside=False):
    if row["recommended_D_U"] is None:
        return "none"
    if row["log_distance"] is None:
        return "unresolved"
    if describe_inside and row["inside_interval"]:
        return "inside"
    prefix = r"\geq " if row["distance_status"] == "censored_distance_lower_bound" else ""
    return "$" + prefix + f"{row['log_distance']:.3f}" + "$"


def recommendation_cell(row):
    if row["recommended_D_U"] is None:
        return "none"
    return (f"{row['recommended_D_U']/1000:.3f}" + r"\newline ("
            + distance_cell(row, describe_inside=True) + ")")


def columns(weights, *, elastic=False):
    """Paragraph widths plus padding sum to textwidth in either environment."""
    padding = 2 * (len(weights) - 1)
    specs = [r">{\raggedright\arraybackslash\hspace{0pt}}p{\dimexpr "
             + f"{w/sum(weights):.9f}" + r"\textwidth-"
             + f"{padding*w/sum(weights):.9f}" + r"\tabcolsep\relax}"
             for w in weights]
    return (r"@{\extracolsep{\fill}}" if elastic else "@{}") + "".join(specs) + "@{}"


def render_main_table(requests):
    validate_requests(requests)
    lines = [GENERATED, r"\begin{table}[!htbp]", r"\centering\scriptsize",
             r"\captionsetup{font=scriptsize}", r"\setlength{\tabcolsep}{2pt}",
             r"\renewcommand{\arraystretch}{0.95}",
             r"\caption{" + MAIN_CAPTION + "}", r"\label{tab:dreq-main}",
             r"\begin{tabular*}{\textwidth}{" + columns([10, 7, 7, 23, 14, 13, 13, 13], elastic=True) + "}",
             r"\toprule",
             r"Readout & Student & Budget (k tokens) & Outcome & Measured interval (k independent tokens) & "
             r"\multicolumn{3}{c@{}}{Recommended pool (k independent tokens)} \\",
             r" & & & & & Boundary relation & Fixed reuse & Per-student interpolation \\",
             r"\midrule"]
    for index, readout in enumerate(READOUTS):
        if index:
            lines.append(r"\addlinespace[2pt]")
        for row in ordered_requests(requests, readout, PRIMARY_TAU):
            cells = [READOUTS[readout], STUDENTS[row["student"]],
                     f"{row['nominal_supervised_tokens']/1000:g}",
                     OUTCOMES[row["measured_crossing"]["status"]], interval_cell(row)]
            cells.extend(recommendation_cell(row["recommendations"]["boundary"][method]) for method in METHODS)
            lines.append(" & ".join(cells) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular*}", r"\end{table}"])
    return "\n".join(lines) + "\n"


FULL_HEADER = (
    r"Student & Budget (k tokens) & Loss tolerance (nats) & Outcome and measured interval (k independent tokens) & "
    r"Log interval width & Boundary relation & Fixed reuse & Per-student interpolation \\"
)


def render_table(requests):
    """Full accounting: one multipage longtable, 144 rows and six group headings."""
    validate_requests(requests)
    lines = [GENERATED, r"\begingroup", r"\normalfont\scriptsize",
             r"\setlength{\tabcolsep}{3pt}", r"\setlength{\LTleft}{0pt plus 1fill}",
             r"\setlength{\LTright}{0pt plus 1fill}", r"\setlength{\LTcapwidth}{\textwidth}",
             r"\begin{longtable}{" + columns([8, 7, 9, 27, 10, 13, 13, 13]) + "}",
             r"\caption{" + FULL_CAPTION + r"}\label{tab:dreq-full}\\",
             r"\toprule", FULL_HEADER, r"\midrule", r"\endfirsthead",
             r"\toprule", FULL_HEADER, r"\midrule", r"\endhead",
             r"\midrule", r"\multicolumn{8}{r@{}}{Continued on the next page.} \\",
             r"\endfoot", r"\bottomrule", r"\endlastfoot"]
    for readout, name in READOUTS.items():
        lines.extend([r"\addlinespace[3pt]",
                      r"\multicolumn{8}{@{}l@{}}{\textbf{" + name + r"}} \\*"])
        for row in ordered_requests(requests, readout):
            width = (f"${row['interval_log_width']:.3f}$" if row["width_status"] == "finite" else
                     "unbounded" if row["width_status"] == "unbounded_log_interval" else "unresolved")
            distances = [r"\newline ".join(f"{name}: " + distance_cell(row["recommendations"][kind][method])
                                          for kind, name in (("boundary", "boundary"), ("delta", "loss")))
                         for method in METHODS]
            cells = [STUDENTS[row["student"]], f"{row['nominal_supervised_tokens']/1000:g}",
                     f"{row['tau']:g}", OUTCOMES[row["measured_crossing"]["status"]] +
                     r"\newline " + interval_cell(row), width, *distances]
            lines.append(" & ".join(cells) + r" \\")
    lines.extend([r"\end{longtable}", r"\endgroup"])
    return "\n".join(lines) + "\n"


def generate(root=ROOT, accounting=None):
    root = Path(root).resolve()
    audit = Artifacts(root)
    saved = audit.read(ACCOUNTING)
    if accounting is not None and accounting["requests"] != saved["requests"]:
        raise ValueError("Supplied accounting differs from the saved A13 evidence")
    accounting = saved
    if accounting["primary_tau"] != PRIMARY_TAU:
        raise ValueError("Primary tolerance changed")
    requests = accounting["requests"]
    validate_requests(requests)
    files = []
    for stem, render, selected, kinds in (
        ("dreq_main", render_main_table, [r for r in requests if r["tau"] == PRIMARY_TAU], ["boundary"]),
        ("dreq_full", render_table, requests, ["boundary", "delta"]),
    ):
        path = output_path(root, "tables", stem + ".tex")
        path.parent.mkdir(parents=True, exist_ok=True)
        text = render(requests)
        path.write_text(house_style(text))
        sidecar = path.with_suffix(".json")
        sidecar.write_text(json.dumps({
            "generator": "analysis/a13_dreq_table.py",
            "renderer": "analysis/a13_dreq_table.py:" + render.__name__,
            "layout": "single-page tabular*" if stem == "dreq_main" else "multipage longtable",
            "input_sha256": {**accounting["input_sha256"], **audit.inputs},
            "accounting_input_sha256": audit.inputs,
            "table_sha256": hashlib.sha256(text.encode()).hexdigest(),
            "label": "tab:" + stem.replace("_", "-"),
            "n_requests": len(selected), "method_cell_order": kinds,
            "primary_tau": PRIMARY_TAU, "student_family": "Gemma 3",
            "budget_units": "thousands of supervised training tokens, including reuse",
            "pool_size_units": "thousands of independent supervised tokens",
            "distance_units": "natural log of independent supervised-token ratios",
            "definitions": accounting["definitions"], "requests": selected,
        }, indent=2, allow_nan=False) + "\n")
        sources = path.with_name(stem + "_sources.md")
        sources.write_text(
            "# " + ("Primary" if stem == "dreq_main" else "Full") + " data-requirement table\n\n"
            + f"Rendered directly from saved A13 accounting; {len(selected)} distinct requests. "
            + ("Only the primary tolerance and boundary recommendations are displayed. " if stem == "dreq_main" else
               "All four tolerances and both boundary and loss recommendation rules are displayed. ")
            + f"Exact recommendations, success flags, censoring, widths and source definitions remain in {sidecar.name}. "
            + "Unresolved measured intervals never become zero distances; abstentions remain explicit.\n\n"
            + "## Direct accounting input\n\n"
            + "\n".join(f"- `{p}`: `{h}`" for p, h in audit.inputs.items())
            + "\n\n## Upstream hashes recorded by A13\n\n"
            + "\n".join(f"- `{p}`: `{h}`" for p, h in accounting["input_sha256"].items()) + "\n")
        files.extend([path, sidecar, sources])
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    for path in generate(args.root):
        print(path)


if __name__ == "__main__":
    main()
