"""Appendix table for the independent cross-method selection validation (C86).

Reads only results/s3-selection-validation/{score_v2.json,plan_v2.json} and writes
paper/paper/tables/s3_selection.tex. CPU only; no fitting, no measurement.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "paper" / "tables" / "s3_selection.tex"
ORDER = ["pythia-410m--step120000", "pythia-1.4b--step120000", "gemma3-1b", "gemma3-4b"]
NAMES = {"pythia-410m--step120000": "Pythia 410M, step 120000",
         "pythia-1.4b--step120000": "Pythia 1.4B, step 120000",
         "gemma3-1b": "Gemma 3, 1B", "gemma3-4b": "Gemma 3, 4B"}
OBJECTIVES = [("math", "Mathematics"), ("code", "Code"),
              ("qa", "Question answering"), ("multi", "Largest increase")]


def fmt(x):
    return "--" if x is None else f"{x:.3f}"


def render():
    score = json.loads((ROOT / "results/s3-selection-validation/score_v2.json").read_text())
    plan = json.loads((ROOT / "results/s3-selection-validation/plan_v2.json").read_text())
    if score["status"] != "COMPLETE":
        raise SystemExit(f"Scoring is {score['status']}; no table is written")
    if plan["predictions_sha256"] is None or plan["maps_sha256"] is None:
        raise SystemExit("Plan carries no numeric seal")
    refs = {r["reference"]: r for r in score["references"]}
    rows = []
    for key in ORDER:
        r = refs[key]
        for i, (obj, label) in enumerate(OBJECTIVES):
            o = r["objectives"][obj]
            rule = o["policies"]["rule"]["mean_paired_regret"]
            quant = o["policies"]["quant-only"]["mean_paired_regret"]
            name = NAMES[key] if i == 0 else ""
            rows.append(f"{name} & {label} & {fmt(o.get('mean_opportunity'))} & "
                        f"{fmt(rule)} & {fmt(quant)} \\\\")
        if key != ORDER[-1]:
            rows.append(r"\midrule")
    caption = (
        "Independent cross-method selection validation on four references that entered no earlier "
        "fit, each with twelve candidates at seventeen storage budgets and a distillation candidate "
        "trained in this round. The opportunity is the loss of the best feasible quantization "
        "candidate minus the loss of the best feasible candidate of any method; the regret of a "
        "policy is the loss of its own frozen choice minus that same best candidate. All values are "
        "means in nats per native token of that family over the sixteen budgets at which both "
        "policies select, and are never pooled across families. Every reference meets the "
        "registered criterion that the rule's mean regret does not exceed the mean regret of "
        "quantization alone.")
    return ("% Generated by analysis/s3_paper_table.py; do not edit.\n"
            "\\begin{table}[!htbp]\n\\centering\\footnotesize\n"
            f"\\caption{{{caption}}}\n\\label{{tab:s3-selection}}\n"
            "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}llrrr@{}}\n\\toprule\n"
            "Reference & Objective & Opportunity & Rule regret & "
            "Quantization-only regret \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular*}\n\\end{table}\n")


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT}")
