"""Appendix table for the independent cross-method selection validation (C86).

Reads only results/s3-selection-validation/{score_v2.json,plan_v2.json} and writes
paper/paper/tables/s3_selection.tex. CPU only; no fitting, no measurement.
"""
import json
from pathlib import Path

try:
    from .paper_table_layout import house_style
except ImportError:  # run as a script
    import sys, pathlib
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    from paper_table_layout import house_style


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper" / "paper" / "tables" / "s3_selection.tex"
ORDER = ["pythia-410m--step120000", "pythia-1.4b--step120000", "gemma3-1b", "gemma3-4b"]
NAMES = {"pythia-410m--step120000": "Pythia 410M, step 120000",
         "pythia-1.4b--step120000": "Pythia 1.4B, step 120000",
         "gemma3-1b": "Gemma 3, 1B", "gemma3-4b": "Gemma 3, 4B"}
OBJECTIVES = [("math", "Mathematics"), ("code", "Code"),
              ("qa", "Question answering"), ("multi", "Largest increase")]


def fmt(x):
    return "--" if x is None else f"{x:.3f}"


def render():
    return house_style(_render())


def _render():
    score = json.loads((ROOT / "results/s3-selection-validation/score_v2.json").read_text())
    plan = json.loads((ROOT / "results/s3-selection-validation/plan_v2.json").read_text())
    if score["status"] != "COMPLETE":
        raise SystemExit(f"Scoring is {score['status']}; no table is written")
    if plan["predictions_sha256"] is None or plan["maps_sha256"] is None:
        raise SystemExit("Plan carries no numeric seal")
    refs = {r["reference"]: r for r in score["references"]}
    rows = []
    for key in ORDER:
        r = refs[key]
        for i, (obj, label) in enumerate(OBJECTIVES):
            o = r["objectives"][obj]
            rule = o["policies"]["rule"]["mean_paired_regret"]
            quant = o["policies"]["quant-only"]["mean_paired_regret"]
            name = NAMES[key] if i == 0 else ""
            rows.append(f"{name} & {label} & {fmt(o.get('mean_opportunity'))} & "
                        f"{fmt(rule)} & {fmt(quant)} \\\\")
        if key != ORDER[-1]:
            rows.append(r"\midrule")
    caption = (
        "Independent cross-method selection validation. None of the four references supplied an "
        "intervention outcome to the rule, and each carries twelve candidates at seventeen storage budgets, "
        "including a distillation candidate trained in this round. Opportunity is the loss of the "
        "best feasible quantization candidate minus that of the best feasible candidate across all "
        "methods; policy regret is the loss of the candidate that policy selected minus that same "
        "all-method optimum. All values are "
        "means in nats per native token of that family over the sixteen budgets at which both "
        "policies find a feasible candidate, and are never pooled across families; no quantization "
        "setting fits the smallest budget. All four references meet the registered criterion, which "
        "compares the two policies per reference after averaging over the four objectives. Read by "
        "objective, the rule is ahead or level throughout except code on Gemma 3, 1B, where it is "
        "0.0001 nats behind.")
    return ("% Generated by analysis/s3_paper_table.py; do not edit.\n"
            "\\begin{table}[tb]\n\\centering\\footnotesize\n"
            f"\\caption{{{caption}}}\n\\label{{tab:s3-selection}}\n"
            "\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}llrrr@{}}\n\\toprule\n"
            "Reference & Objective & Opportunity & Rule regret & "
            "Quantization-only regret \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular*}\n\\end{table}\n")


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT}")
