#!/usr/bin/env python3
"""Round-3 deliverable tables (CPU): pruning (v53) and grouped quantization (v55) — formula, parameters, dev/test ranges,
per-capability test MAE, gain vs strongest same-input and source-free baselines, signed bias; coefficient tables."""

try:
    from .paper_table_text import table_text as publication_table_text
except ImportError:  # Direct scripts and file-based imports.
    try:
        from analysis.paper_table_text import table_text as publication_table_text
    except ImportError:
        from paper_table_text import table_text as publication_table_text

import json, math
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; TAB = ROOT / "paper/paper/tables"; C = ("math", "code", "qa")
f3 = lambda v: f"{v:.3f}"; s3 = lambda v: f"{v:+.3f}"
# ---------------- pruning (v53) ----------------
reg = json.load(open(ROOT / "results/v53-prune-dev/register.json")); tags = ["pythia-410m@step48000", "pythia-1.4b@step112000", "pythia-6.9b@step80000"]
cmp = {t: json.load(open(ROOT / f"results/v53-prune-dev/compare_{t}.json")) for t in tags}
pred = {t: json.load(open(ROOT / f"results/v53-prune-dev/predictions_{t}.json")) for t in tags}
PC = ["power", "A2", "A1", "cont", "strength_only", "median_curve", "zero"]
FORM = {"power": r"$(\beta_c\!\cdot\!\phi)\,((1-d)/0.3)^{\gamma_c}$", "A2": r"per-$d$ OLS on $\phi$ at 5 anchors + linear interp.", "A1": r"power form, $\gamma_c{=}1$",
        "cont": r"$(\beta_c\!\cdot\!\phi)s+(\zeta_c\!\cdot\!\phi)s^2$, $s{=}1{-}d$", "strength_only": r"$A((1-d)/0.3)^{\gamma}$ (source-free)", "median_curve": "median dev curve (source-free)", "zero": "zero change"}
NP = {"power": 5, "A2": 20, "A1": 4, "cont": 8, "strength_only": 2, "median_curve": 0, "zero": 0}
def err(t, k, c):  # list of signed errors pred-obs over densities
    return [pred[t]["predictions"][c][d][k] - cmp[t]["observed_delta_loss"][c][d] for d in ("0.85", "0.675", "0.575")]
mae = {k: {c: sum(abs(e) for t in tags for e in err(t, k, c)) / 9 for c in C} for k in PC}
bias = {k: {c: sum(e for t in tags for e in err(t, k, c)) / 9 for c in C} for k in PC}
L = [r"\begin{table}[t]\centering\footnotesize\setlength{\tabcolsep}{3pt}", r"\begin{tabular}{@{}lrrrrrrr@{}}", r"\toprule",
     r"Candidate & $P$ & \multicolumn{3}{c}{test MAE} & \multicolumn{3}{c}{signed bias (pred.\ $-$ obs.)} \\", r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}", r" & & math & code & QA & math & code & QA \\", r"\midrule"]
for k in PC:
    lab = (r"\textbf{power (selected)}" if k == "power" else k.replace("_", " ")); L.append(f"{lab} & {NP[k]} & " + " & ".join(f3(mae[k][c]) for c in C) + " & " + " & ".join(s3(bias[k][c]) for c in C) + r" \\")
gain_txt = "Gain of the selected form vs A2 (same input): " + ", ".join(f"{c} {s3(mae['A2'][c]-mae['power'][c])}" for c in C) + "; vs the strongest source-free curve: " + ", ".join(f"{c} {s3(min(mae[b][c] for b in ('strength_only','median_curve','zero'))-mae['power'][c])}" for c in C) + ". "
L += [
      r"\bottomrule\end{tabular}",
      r"\caption{Round-3 pruning deliverable. Forms: power $(\beta_c\cdot\phi)((1-d)/0.3)^{\gamma_c}$; A2 = per-density OLS on $\phi$ at five anchors with linear interpolation; A1 = power form with $\gamma_c{=}1$; cont $=(\beta_c\cdot\phi)s+(\zeta_c\cdot\phi)s^2$, $s{=}1{-}d$; strength-only $A((1-d)/0.3)^{\gamma}$, the median development curve, and zero change are source-free. Inputs $\phi=[1,\tilde{\log N_0},\tilde L_{0,c},\tilde{\log D_0}]$ (standardized on the development set); development set = 17 Pythia states (160M--6.9B, steps 16k--143k, densities $\ge0.55$); the selected form was chosen by a pre-committed leave-one-source-out rule (tie within 0.02 nats resolved toward the continuous, zero-at-$d{=}1$ form with fewer parameters). Test = three new checkpoints (410M@48k, 1.4B@112k, 6.9B@80k) at $d\in\{0.85,0.675,0.575\}$, predictions committed before measurement; MAE and mean signed error (prediction minus observation) over nine cells per capability. Coefficients in Appendix Table~\ref{tab:round3_coef}. " + gain_txt + r"Generated by \texttt{v57\_round3\_tables.py}.}",
      r"\label{tab:round3_prune}\end{table}"]
(TAB / "round3_prune.tex").write_text(publication_table_text("\n".join(L) + "\n"))
# coefficient table (selected pruning form + standardization)
st = reg["standardization"]; L = [r"\begin{table}[H]\centering\footnotesize", r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule", r"capability & $\gamma_c$ & $\beta_{c,0}$ & $\beta_{c,\log N_0}$ & $\beta_{c,L_0}$ & $\beta_{c,\log D_0}$ \\", r"\midrule"]
for c in C:
    m = reg["models"][c]["power"]; L.append(f"{c} & {float(m['gamma']):.2f} & " + " & ".join(f"{b:+.3f}" for b in m["beta"]) + r" \\")
L += [r"\bottomrule\end{tabular}", r"\caption{Selected pruning form $\widehat{\Delta L}_c=(\beta_c\cdot\phi)((1-d)/0.3)^{\gamma_c}$ with $\phi=[1,z(\log N_0),z(L_{0,c}),z(\log D_0)]$; standardization centers " + ", ".join(f"{v:.3f}" for v in st["center"]) + " and scales " + ", ".join(f"{v:.3f}" for v in st["scale"]) + r" for $(\log N_0, L_{0,c}, \log D_0)$ in natural units ($N_0$ = transformer weight-matrix parameters, $D_0$ = tokens). Register: \texttt{v53-prune-dev/register.json}.}", r"\label{tab:round3_coef}\end{table}"]
(TAB / "round3_coef.tex").write_text(publication_table_text("\n".join(L) + "\n"))
# ---------------- quantization (v55) ----------------
c5 = json.load(open(ROOT / "results/v55-quant-group/compare.json")); r5 = json.load(open(ROOT / "results/v55-quant-group/register.json"))
QC = ["low_order_2d", "separable", "same_input_interpolation", "median", "mean", "zero"]
QF = {"low_order_2d": r"$\phi\cdot[1,u,v,uv,u^2]$ ($u{=}\log_2 q_{\max}$ centred, $v{=}\log_2 g/128$)", "separable": r"$(\beta_c\!\cdot\!\phi)\,q_{\max}^{-p_c}(g/128)^{q_c}$", "same_input_interpolation": "bilinear between the 4 dev configs (same input)", "median": "per-config median, interpolated (source-free)", "mean": "per-config mean, interpolated", "zero": "zero change"}
QP = {"low_order_2d": 20, "separable": 6, "same_input_interpolation": 16, "median": 0, "mean": 0, "zero": 0}
rows = c5["rows"]
def cell_err(row, k):
    return row["predictions"][k] - row["dL"]
L = [r"\begin{table}[t]\centering\footnotesize\setlength{\tabcolsep}{2.5pt}", r"\begin{tabular}{@{}lr" + "rrr" * 3 + r"@{}}", r"\toprule",
     r"Candidate & $P$ & \multicolumn{3}{c}{bit test (12)} & \multicolumn{3}{c}{granularity test (18)} & \multicolumn{3}{c}{joint, 1B@96k (3)} \\", r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}\cmidrule(lr){9-11}", r" & & math & code & QA & math & code & QA & math & code & QA \\", r"\midrule"]
tsets = ("bit_test", "granularity_test", "joint_test"); M = {}
for k in QC:
    cells = []
    for ts in tsets:
        for c in C:
            rr = [r for r in rows if r.get("test_set", r.get("test")) == ts and r.get("capability", r.get("cap")) == c]
            e = [cell_err(r, k) for r in rr]; M[(k, ts, c)] = (sum(abs(x) for x in e) / len(e) if e else float("nan"), sum(e) / len(e) if e else float("nan"))
            cells.append(f3(M[(k, ts, c)][0]))
    L.append((r"\textbf{low-order 2D}" if k == "low_order_2d" else k.replace("_", " ")) + f" & {QP[k]} & " + " & ".join(cells) + r" \\")
bias_txt = "Signed bias of the 2D form (math/code/QA): " + "; ".join(f"{ts.split('_')[0]} " + "/".join(s3(M[('low_order_2d', ts, c)][1]) for c in C) for ts in tsets) + ". "
L += [
      r"\bottomrule\end{tabular}",
      r"\caption{Round-3 grouped-quantization deliverable (MAE, nats). Forms: low-order 2D $=\phi\cdot[1,u,v,uv,u^2]$ with $u=\log_2 q_{\max}$ (centred) and $v=\log_2(g/128)$, one 4-vector of state coefficients per term; separable $=(\beta_c\cdot\phi)\,q_{\max}^{-p_c}(g/128)^{q_c}$; same-input interpolation = bilinear between the four development configurations; median and mean = per-configuration statistics interpolated the same way (source-free). Same inputs $\phi$ as Table~\ref{tab:round3_prune}; development = six Pythia states (160M/410M/1.4B at steps 16k and 143k) $\times$ $b\in\{3,5\}$ $\times$ $g\in\{64,256\}$ under symmetric round-to-nearest with contiguous input groups of $g$ weights; all predictions committed before the tests. Bit test: unseen $b{=}4$ at $g\in\{64,256\}$ on the dev states; granularity test: unseen $g{=}128$ at $b\in\{3,4,5\}$ on the dev states; joint test: new state 1B@96k at $g{=}128$. All candidates and baselines are reported on every test (pre-committed rule; no selection by outcome). " + bias_txt + r"Generated by \texttt{v57\_round3\_tables.py}.}",
      r"\label{tab:round3_quant}\end{table}"]
(TAB / "round3_quant.tex").write_text(publication_table_text("\n".join(L) + "\n"))
print("wrote round3_prune.tex, round3_coef.tex, round3_quant.tex"); print("prune MAE:", {k: {c: round(mae[k][c], 3) for c in C} for k in ("power", "A2", "median_curve")}); print("quant 2D:", {ts: {c: round(M[('low_order_2d', ts, c)][0], 3) for c in C} for ts in tsets})
